# Generated by Django 3.1.1 on 2020-09-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_auto_20200924_0905'),
        ('comentarios', '0002_auto_20200924_0905'),
        ('pontosturisticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.Avaliacoes'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentarios'),
        ),
    ]
