# Generated by Django 3.1.1 on 2020-09-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontosturisticos', '0004_auto_20200924_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontosturisticos'),
        ),
    ]
